version: '3.1'
services:
  db:
    image: postgres:latest
    restart: "no"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}  # Opcional, si quieres definir un usuario específico
      POSTGRES_DB: ${POSTGRES_DB}      # Opcional, si quieres definir una base de datos específica
    networks:
      - skynet
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    #volumes:
     # - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

  adminer:
    image: adminer
    restart: "no"
    networks:
      - skynet
    ports:
      - ${ADMINER_HOST_PORT}:8080
    
networks:
  skynet: